/*
 * Pixel Dungeon
 * Copyright (C) 2012-2015 Oleg Dolya
 *
 * Yet Another Pixel Dungeon
 * Copyright (C) 2015-2019 Considered Hamster
 *
 * No Name Yet Pixel Dungeon
 * Copyright (C) 2018-2019 RavenWolf
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
package com.ravenwolf.nnypd.actors.hero;

import com.watabou.utils.Bundle;

public enum HeroSubClass {

	NONE( null, null ),
	

/*	KNIGHT( "knight",
			"The _Knight_ is a sturdy combatant that excels using defencive stances and counter attacks. " +
					"Guard buff will not be decreased while moving and they will deal bonus counter attack damage. " +
					"\n_Relentless assault bonus:_ perform an additional strike and activate guard." ),
	BERSERKER( "berserker",
			"The _Berserker_ is a fierce warrior that will enters a state of frenzy when receiving large wounds, " +
					"increasing its physical damage. Chances and grow rate or Frenzy rises the lower the health of the hero." +
					"\n_Relentless assault bonus:_ the last strike will deal 33% additional damage and will damage enemies around the main target." ),*/
	KNIGHT( "圣骑士",
			"_圣骑士_是一名强壮的战士，擅长使用格挡和反击。" +
					"移动时会维持原本的持盾状态，并且反击时会造成额外的反击伤害。 " +
					"\n_毁灭打击加成:_ 额外进行一次的攻击并进入持盾状态。" ),
	BERSERKER( "狂战士",
			"_狂战士_是一名凶猛的战士，受到重伤时会进入狂怒状态， " +
					"增加它的物理伤害。狂战士的生命值越低，狂怒的概率和增益就会越高。" +
					"\n_毁灭打击加成:_ 最后一次攻击将造成33%的额外伤害，并对主要目标周围的敌人造成伤害。" ),

/*	CONJURER( "conjurer",
			"_Conjurers_ are masters of controlling arcane sources and magical beings. When zapping wands or charms " +
					"the conjurer will imbue itself and their allies with a protective barrier based on spent charges. " +
					"They also receive a 10% bonus in willpower." +
					"\n_Overload bonus:_ increase overload duration, and boost the efficiency of rings by 20% when overloaded." ),
	BATTLEMAGE( "battlemage",
			"The _Battlemage_ specialize on combining wands zaps with physical attacks. Enemies struck by wand zaps will be revealed, " +
					" reducing their defencive capabilities. The battlemage can also empower its wands with momentum generated by melee attacks, " +
					"increasing their damage by 10% per combo point." +
					"\n_Overload bonus:_ while overloaded melee attacks will deal bonus energy damage." ),*/
	CONJURER( "术士",
			"_术士_是控制奥术能量和魔法生物的强大魔法师。使用法杖或魔咒时， " +
					"术士会根据消耗的充能为自己和他的盟友注入一道保护屏障。 " +
					"并且他还拥有额外10%的意志加成。" +
					"\n_过载加成:_ 延长过载的持续时间，并且过载期间佩戴的戒指效果会增加20%" ),
	BATTLEMAGE( "战斗法师",
			"_战斗法师_擅长将法术与物理攻击相结合。 被法杖攻击的敌人将会被标记，" +
					"并且防御力下降。战斗法师还能通过近战攻击产生的能量来增强他的法杖，" +
					"每次连击都会增加法杖10%的伤害" +
					"\n_过载加成:_ 过载时战斗法师的近战攻击将造成额外的法术伤害" ),

/*	ASSASSIN( "assassin",
					   "_Assassins_ are masters of stealth and guile, skilled at killing in shadows both with melee and ranged weapons. " +
							   "Its sneak attacks will deal 25% more damage and wont alert nearby enemies when fighting. " +
							   "\n_Shadow strike bonus:_ deal additional damage based on enemy missing health." ),
	SLAYER( "slayer",
						"Due to its lightning reflexes the _Slayer_, have chances to counter attack after successfully dodging a melee strike, " +
						"and its evasion is not reduced when surrounded or near impassable terrain. " +
								"Combo points will also increase critical chance of his attacks." +
						"\n_Shadow strike bonus:_ strike up to four enemies near the main target dealing 66% weapon damage." ),*/
	ASSASSIN( "刺客",
					   "_刺客_是潜行和刺杀方面的强者，擅长在暗处用近战和远程武器来暗杀敌人。 " +
							   "刺客的伏击伤害会增加25%，并且在战斗时不会惊醒附近的敌人。 " +
							   "\n_暗影突袭加成:_ 基于敌人的已损失生命值造成额外伤害。" ),
	SLAYER( "猎杀者",
						"_猎杀者_拥有闪电般的反应能力，使得他在成功躲避近战攻击后有机会反击敌人， " +
						"即便是处于狭隘地形或被包围时，它的闪避能力也不会有丝毫下降。 " +
								"连击会增加他打出暴击的概率。" +
						"\n_暗影突袭加成:_在攻击主目标时最多攻击附近的4名敌人，造成66%的武器伤害。" ),

/*	SNIPER( "ranger",
			"_Rangers_ specializes almost exclusively on ranged combat, they can see further in the darkness of the dungeon, becoming very deadly at distance. " +
					"Their sight range is increased by 1 tile, and have 10% more chances to score critical hits with ranged weapons." +
					" \n_Spectral blades bonus:_ hurls 2 additional blades and every enemy in the area can be struck twice." ),
	AMAZON( "amazon",
			"The _Amazon_ is a versatile warrior that can quickly switch from ranged to melee combat. Taking advantage of shields and defencive tactics. " +
					"Guard duration is increased by one turn, and when equiping a shield the amazon will automatically activate guard." +
					" \n_Spectral blades bonus:_ While revealed, enemies will receive 33% more damage from melee attacks." );*/
	SNIPER( "神射手",
					"_神射手_专门从事远程作战，她可以在黑暗的地牢中看得更远，使远程攻击更加致命。 " +
					"她的视野范围增加1格，在使用远程武器时暴击几率增加10%。" +
					" \n_幻影飞刀加成:_ 投掷2把额外的幻影之刃，范围内每个敌人都可以被击中两次。" ),
	AMAZON( "女武神",
					"_女武神_是一名灵活多变的女战士，可以快速从远程切换到近战。善于利用盾牌来防御。" +
					"格挡时间会额外增加一个回合，装备上盾牌时，女武神会自动进入格挡状态。" +
					" \n_幻影飞刀加成:_ 当敌人被标记时，女武神的近战攻击会增加额外33%的伤害。" );
	
	private String title;
	private String desc;
	
	HeroSubClass(String title, String desc) {
		this.title = title;
		this.desc = desc;
	}
	
	public String title() {
		return title;
	}
	
	public String desc() {
		return desc;
	}
	
	private static final String SUBCLASS	= "subClass";
	
	public void storeInBundle( Bundle bundle ) {
		bundle.put( SUBCLASS, toString() );
	}
	
	public static HeroSubClass restoreInBundle( Bundle bundle ) {
		String value = bundle.getString( SUBCLASS );
		try {
			return valueOf( value );
		} catch (Exception e) {
			return NONE;
		}
	}
	
}
